package com.example.warehouseinventoryapp.provider;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "items")
public class Item {

    @PrimaryKey(autoGenerate = true)
    @NonNull
    @ColumnInfo(name = "itemID")
    private int itemID;

    @ColumnInfo(name = "itemName")
    private String itemName;

    @ColumnInfo(name = "itemQuantity")
    private int itemQuantity;

    @ColumnInfo(name = "itemCost")
    private double itemCost;

    @ColumnInfo(name = "itemDescription")
    private String itemDescription;

    @ColumnInfo(name = "itemFrozen")
    private boolean itemFrozen;

    public Item(String itemName, int itemQuantity, double itemCost, String itemDescription, boolean itemFrozen) {
        //no need to initialise itemID since it is autogenerated
        this.itemName = itemName;
        this.itemQuantity = itemQuantity;
        this.itemCost = itemCost;
        this.itemDescription = itemDescription;
        this.itemFrozen = itemFrozen;
    }

    public int getItemID() {
        return itemID;
    }

    public void setItemID(@NonNull int itemID) {
        this.itemID = itemID;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public int getItemQuantity() {
        return itemQuantity;
    }

    public void setItemQuantity(int itemQuantity) {
        this.itemQuantity = itemQuantity;
    }

    public double getItemCost() {
        return itemCost;
    }

    public void setItemCost(double itemCost) {
        this.itemCost = itemCost;
    }

    public String getItemDescription() {
        return itemDescription;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    public boolean isItemFrozen() {
        return itemFrozen;
    }

    public void setItemFrozen(boolean itemFrozen) {
        this.itemFrozen = itemFrozen;
    }
}
